# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/59187/OneDrive - CAF/99_privado/relojes/typst"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/59187/OneDrive - CAF/99_privado/relojes/typst"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/59187/OneDrive - CAF/99_privado/relojes/typst/CMakeFiles" "/mnt/c/Users/59187/OneDrive - CAF/99_privado/relojes/typst//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/59187/OneDrive - CAF/99_privado/relojes/typst/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pdf-ala14

# Build rule for target.
pdf-ala14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-ala14
.PHONY : pdf-ala14

# fast build rule for target.
pdf-ala14/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-ala14.dir/build.make CMakeFiles/pdf-ala14.dir/build
.PHONY : pdf-ala14/fast

#=============================================================================
# Target rules for targets named png-ala14

# Build rule for target.
png-ala14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-ala14
.PHONY : png-ala14

# fast build rule for target.
png-ala14/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-ala14.dir/build.make CMakeFiles/png-ala14.dir/build
.PHONY : png-ala14/fast

#=============================================================================
# Target rules for targets named pdf-bushido

# Build rule for target.
pdf-bushido: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-bushido
.PHONY : pdf-bushido

# fast build rule for target.
pdf-bushido/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-bushido.dir/build.make CMakeFiles/pdf-bushido.dir/build
.PHONY : pdf-bushido/fast

#=============================================================================
# Target rules for targets named png-bushido

# Build rule for target.
png-bushido: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-bushido
.PHONY : png-bushido

# fast build rule for target.
png-bushido/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-bushido.dir/build.make CMakeFiles/png-bushido.dir/build
.PHONY : png-bushido/fast

#=============================================================================
# Target rules for targets named pdf-caballero

# Build rule for target.
pdf-caballero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-caballero
.PHONY : pdf-caballero

# fast build rule for target.
pdf-caballero/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-caballero.dir/build.make CMakeFiles/pdf-caballero.dir/build
.PHONY : pdf-caballero/fast

#=============================================================================
# Target rules for targets named png-caballero

# Build rule for target.
png-caballero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-caballero
.PHONY : png-caballero

# fast build rule for target.
png-caballero/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-caballero.dir/build.make CMakeFiles/png-caballero.dir/build
.PHONY : png-caballero/fast

#=============================================================================
# Target rules for targets named pdf-colossus

# Build rule for target.
pdf-colossus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-colossus
.PHONY : pdf-colossus

# fast build rule for target.
pdf-colossus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-colossus.dir/build.make CMakeFiles/pdf-colossus.dir/build
.PHONY : pdf-colossus/fast

#=============================================================================
# Target rules for targets named png-colossus

# Build rule for target.
png-colossus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-colossus
.PHONY : png-colossus

# fast build rule for target.
png-colossus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-colossus.dir/build.make CMakeFiles/png-colossus.dir/build
.PHONY : png-colossus/fast

#=============================================================================
# Target rules for targets named pdf-competidor

# Build rule for target.
pdf-competidor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-competidor
.PHONY : pdf-competidor

# fast build rule for target.
pdf-competidor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-competidor.dir/build.make CMakeFiles/pdf-competidor.dir/build
.PHONY : pdf-competidor/fast

#=============================================================================
# Target rules for targets named png-competidor

# Build rule for target.
png-competidor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-competidor
.PHONY : png-competidor

# fast build rule for target.
png-competidor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-competidor.dir/build.make CMakeFiles/png-competidor.dir/build
.PHONY : png-competidor/fast

#=============================================================================
# Target rules for targets named pdf-cosmotemp

# Build rule for target.
pdf-cosmotemp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-cosmotemp
.PHONY : pdf-cosmotemp

# fast build rule for target.
pdf-cosmotemp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-cosmotemp.dir/build.make CMakeFiles/pdf-cosmotemp.dir/build
.PHONY : pdf-cosmotemp/fast

#=============================================================================
# Target rules for targets named png-cosmotemp

# Build rule for target.
png-cosmotemp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-cosmotemp
.PHONY : png-cosmotemp

# fast build rule for target.
png-cosmotemp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-cosmotemp.dir/build.make CMakeFiles/png-cosmotemp.dir/build
.PHONY : png-cosmotemp/fast

#=============================================================================
# Target rules for targets named pdf-decotimer

# Build rule for target.
pdf-decotimer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-decotimer
.PHONY : pdf-decotimer

# fast build rule for target.
pdf-decotimer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-decotimer.dir/build.make CMakeFiles/pdf-decotimer.dir/build
.PHONY : pdf-decotimer/fast

#=============================================================================
# Target rules for targets named png-decotimer

# Build rule for target.
png-decotimer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-decotimer
.PHONY : png-decotimer

# fast build rule for target.
png-decotimer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-decotimer.dir/build.make CMakeFiles/png-decotimer.dir/build
.PHONY : png-decotimer/fast

#=============================================================================
# Target rules for targets named pdf-dirty_fifteen

# Build rule for target.
pdf-dirty_fifteen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-dirty_fifteen
.PHONY : pdf-dirty_fifteen

# fast build rule for target.
pdf-dirty_fifteen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-dirty_fifteen.dir/build.make CMakeFiles/pdf-dirty_fifteen.dir/build
.PHONY : pdf-dirty_fifteen/fast

#=============================================================================
# Target rules for targets named png-dirty_fifteen

# Build rule for target.
png-dirty_fifteen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-dirty_fifteen
.PHONY : png-dirty_fifteen

# fast build rule for target.
png-dirty_fifteen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-dirty_fifteen.dir/build.make CMakeFiles/png-dirty_fifteen.dir/build
.PHONY : png-dirty_fifteen/fast

#=============================================================================
# Target rules for targets named pdf-ferroviario

# Build rule for target.
pdf-ferroviario: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-ferroviario
.PHONY : pdf-ferroviario

# fast build rule for target.
pdf-ferroviario/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-ferroviario.dir/build.make CMakeFiles/pdf-ferroviario.dir/build
.PHONY : pdf-ferroviario/fast

#=============================================================================
# Target rules for targets named png-ferroviario

# Build rule for target.
png-ferroviario: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-ferroviario
.PHONY : png-ferroviario

# fast build rule for target.
png-ferroviario/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-ferroviario.dir/build.make CMakeFiles/png-ferroviario.dir/build
.PHONY : png-ferroviario/fast

#=============================================================================
# Target rules for targets named pdf-forest_defender

# Build rule for target.
pdf-forest_defender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-forest_defender
.PHONY : pdf-forest_defender

# fast build rule for target.
pdf-forest_defender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-forest_defender.dir/build.make CMakeFiles/pdf-forest_defender.dir/build
.PHONY : pdf-forest_defender/fast

#=============================================================================
# Target rules for targets named png-forest_defender

# Build rule for target.
png-forest_defender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-forest_defender
.PHONY : png-forest_defender

# fast build rule for target.
png-forest_defender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-forest_defender.dir/build.make CMakeFiles/png-forest_defender.dir/build
.PHONY : png-forest_defender/fast

#=============================================================================
# Target rules for targets named pdf-galeno

# Build rule for target.
pdf-galeno: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-galeno
.PHONY : pdf-galeno

# fast build rule for target.
pdf-galeno/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-galeno.dir/build.make CMakeFiles/pdf-galeno.dir/build
.PHONY : pdf-galeno/fast

#=============================================================================
# Target rules for targets named png-galeno

# Build rule for target.
png-galeno: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-galeno
.PHONY : png-galeno

# fast build rule for target.
png-galeno/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-galeno.dir/build.make CMakeFiles/png-galeno.dir/build
.PHONY : png-galeno/fast

#=============================================================================
# Target rules for targets named pdf-gamma_gibraltar

# Build rule for target.
pdf-gamma_gibraltar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-gamma_gibraltar
.PHONY : pdf-gamma_gibraltar

# fast build rule for target.
pdf-gamma_gibraltar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-gamma_gibraltar.dir/build.make CMakeFiles/pdf-gamma_gibraltar.dir/build
.PHONY : pdf-gamma_gibraltar/fast

#=============================================================================
# Target rules for targets named png-gamma_gibraltar

# Build rule for target.
png-gamma_gibraltar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-gamma_gibraltar
.PHONY : png-gamma_gibraltar

# fast build rule for target.
png-gamma_gibraltar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-gamma_gibraltar.dir/build.make CMakeFiles/png-gamma_gibraltar.dir/build
.PHONY : png-gamma_gibraltar/fast

#=============================================================================
# Target rules for targets named pdf-goldmaster

# Build rule for target.
pdf-goldmaster: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-goldmaster
.PHONY : pdf-goldmaster

# fast build rule for target.
pdf-goldmaster/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-goldmaster.dir/build.make CMakeFiles/pdf-goldmaster.dir/build
.PHONY : pdf-goldmaster/fast

#=============================================================================
# Target rules for targets named png-goldmaster

# Build rule for target.
png-goldmaster: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-goldmaster
.PHONY : png-goldmaster

# fast build rule for target.
png-goldmaster/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-goldmaster.dir/build.make CMakeFiles/png-goldmaster.dir/build
.PHONY : png-goldmaster/fast

#=============================================================================
# Target rules for targets named pdf-grand_belize

# Build rule for target.
pdf-grand_belize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-grand_belize
.PHONY : pdf-grand_belize

# fast build rule for target.
pdf-grand_belize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-grand_belize.dir/build.make CMakeFiles/pdf-grand_belize.dir/build
.PHONY : pdf-grand_belize/fast

#=============================================================================
# Target rules for targets named png-grand_belize

# Build rule for target.
png-grand_belize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-grand_belize
.PHONY : png-grand_belize

# fast build rule for target.
png-grand_belize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-grand_belize.dir/build.make CMakeFiles/png-grand_belize.dir/build
.PHONY : png-grand_belize/fast

#=============================================================================
# Target rules for targets named pdf-heian

# Build rule for target.
pdf-heian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-heian
.PHONY : pdf-heian

# fast build rule for target.
pdf-heian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-heian.dir/build.make CMakeFiles/pdf-heian.dir/build
.PHONY : pdf-heian/fast

#=============================================================================
# Target rules for targets named png-heian

# Build rule for target.
png-heian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-heian
.PHONY : png-heian

# fast build rule for target.
png-heian/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-heian.dir/build.make CMakeFiles/png-heian.dir/build
.PHONY : png-heian/fast

#=============================================================================
# Target rules for targets named pdf-iberia

# Build rule for target.
pdf-iberia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-iberia
.PHONY : pdf-iberia

# fast build rule for target.
pdf-iberia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-iberia.dir/build.make CMakeFiles/pdf-iberia.dir/build
.PHONY : pdf-iberia/fast

#=============================================================================
# Target rules for targets named png-iberia

# Build rule for target.
png-iberia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-iberia
.PHONY : png-iberia

# fast build rule for target.
png-iberia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-iberia.dir/build.make CMakeFiles/png-iberia.dir/build
.PHONY : png-iberia/fast

#=============================================================================
# Target rules for targets named pdf-ichi

# Build rule for target.
pdf-ichi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-ichi
.PHONY : pdf-ichi

# fast build rule for target.
pdf-ichi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-ichi.dir/build.make CMakeFiles/pdf-ichi.dir/build
.PHONY : pdf-ichi/fast

#=============================================================================
# Target rules for targets named png-ichi

# Build rule for target.
png-ichi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-ichi
.PHONY : png-ichi

# fast build rule for target.
png-ichi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-ichi.dir/build.make CMakeFiles/png-ichi.dir/build
.PHONY : png-ichi/fast

#=============================================================================
# Target rules for targets named pdf-inmortal

# Build rule for target.
pdf-inmortal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-inmortal
.PHONY : pdf-inmortal

# fast build rule for target.
pdf-inmortal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-inmortal.dir/build.make CMakeFiles/pdf-inmortal.dir/build
.PHONY : pdf-inmortal/fast

#=============================================================================
# Target rules for targets named png-inmortal

# Build rule for target.
png-inmortal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-inmortal
.PHONY : png-inmortal

# fast build rule for target.
png-inmortal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-inmortal.dir/build.make CMakeFiles/png-inmortal.dir/build
.PHONY : png-inmortal/fast

#=============================================================================
# Target rules for targets named pdf-inmortal_reserva_especial

# Build rule for target.
pdf-inmortal_reserva_especial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-inmortal_reserva_especial
.PHONY : pdf-inmortal_reserva_especial

# fast build rule for target.
pdf-inmortal_reserva_especial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-inmortal_reserva_especial.dir/build.make CMakeFiles/pdf-inmortal_reserva_especial.dir/build
.PHONY : pdf-inmortal_reserva_especial/fast

#=============================================================================
# Target rules for targets named png-inmortal_reserva_especial

# Build rule for target.
png-inmortal_reserva_especial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-inmortal_reserva_especial
.PHONY : png-inmortal_reserva_especial

# fast build rule for target.
png-inmortal_reserva_especial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-inmortal_reserva_especial.dir/build.make CMakeFiles/png-inmortal_reserva_especial.dir/build
.PHONY : png-inmortal_reserva_especial/fast

#=============================================================================
# Target rules for targets named pdf-kingtuna

# Build rule for target.
pdf-kingtuna: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-kingtuna
.PHONY : pdf-kingtuna

# fast build rule for target.
pdf-kingtuna/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-kingtuna.dir/build.make CMakeFiles/pdf-kingtuna.dir/build
.PHONY : pdf-kingtuna/fast

#=============================================================================
# Target rules for targets named png-kingtuna

# Build rule for target.
png-kingtuna: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-kingtuna
.PHONY : png-kingtuna

# fast build rule for target.
png-kingtuna/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-kingtuna.dir/build.make CMakeFiles/png-kingtuna.dir/build
.PHONY : png-kingtuna/fast

#=============================================================================
# Target rules for targets named pdf-majetek

# Build rule for target.
pdf-majetek: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-majetek
.PHONY : pdf-majetek

# fast build rule for target.
pdf-majetek/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-majetek.dir/build.make CMakeFiles/pdf-majetek.dir/build
.PHONY : pdf-majetek/fast

#=============================================================================
# Target rules for targets named png-majetek

# Build rule for target.
png-majetek: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-majetek
.PHONY : png-majetek

# fast build rule for target.
png-majetek/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-majetek.dir/build.make CMakeFiles/png-majetek.dir/build
.PHONY : png-majetek/fast

#=============================================================================
# Target rules for targets named pdf-monumental

# Build rule for target.
pdf-monumental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-monumental
.PHONY : pdf-monumental

# fast build rule for target.
pdf-monumental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-monumental.dir/build.make CMakeFiles/pdf-monumental.dir/build
.PHONY : pdf-monumental/fast

#=============================================================================
# Target rules for targets named png-monumental

# Build rule for target.
png-monumental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-monumental
.PHONY : png-monumental

# fast build rule for target.
png-monumental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-monumental.dir/build.make CMakeFiles/png-monumental.dir/build
.PHONY : png-monumental/fast

#=============================================================================
# Target rules for targets named pdf-okeah

# Build rule for target.
pdf-okeah: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-okeah
.PHONY : pdf-okeah

# fast build rule for target.
pdf-okeah/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-okeah.dir/build.make CMakeFiles/pdf-okeah.dir/build
.PHONY : pdf-okeah/fast

#=============================================================================
# Target rules for targets named png-okeah

# Build rule for target.
png-okeah: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-okeah
.PHONY : png-okeah

# fast build rule for target.
png-okeah/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-okeah.dir/build.make CMakeFiles/png-okeah.dir/build
.PHONY : png-okeah/fast

#=============================================================================
# Target rules for targets named pdf-racing

# Build rule for target.
pdf-racing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-racing
.PHONY : pdf-racing

# fast build rule for target.
pdf-racing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-racing.dir/build.make CMakeFiles/pdf-racing.dir/build
.PHONY : pdf-racing/fast

#=============================================================================
# Target rules for targets named png-racing

# Build rule for target.
png-racing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-racing
.PHONY : png-racing

# fast build rule for target.
png-racing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-racing.dir/build.make CMakeFiles/png-racing.dir/build
.PHONY : png-racing/fast

#=============================================================================
# Target rules for targets named pdf-roquina

# Build rule for target.
pdf-roquina: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-roquina
.PHONY : pdf-roquina

# fast build rule for target.
pdf-roquina/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-roquina.dir/build.make CMakeFiles/pdf-roquina.dir/build
.PHONY : pdf-roquina/fast

#=============================================================================
# Target rules for targets named png-roquina

# Build rule for target.
png-roquina: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-roquina
.PHONY : png-roquina

# fast build rule for target.
png-roquina/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-roquina.dir/build.make CMakeFiles/png-roquina.dir/build
.PHONY : png-roquina/fast

#=============================================================================
# Target rules for targets named pdf-salto_de_fe

# Build rule for target.
pdf-salto_de_fe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-salto_de_fe
.PHONY : pdf-salto_de_fe

# fast build rule for target.
pdf-salto_de_fe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-salto_de_fe.dir/build.make CMakeFiles/pdf-salto_de_fe.dir/build
.PHONY : pdf-salto_de_fe/fast

#=============================================================================
# Target rules for targets named png-salto_de_fe

# Build rule for target.
png-salto_de_fe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-salto_de_fe
.PHONY : png-salto_de_fe

# fast build rule for target.
png-salto_de_fe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-salto_de_fe.dir/build.make CMakeFiles/png-salto_de_fe.dir/build
.PHONY : png-salto_de_fe/fast

#=============================================================================
# Target rules for targets named pdf-sevenseas

# Build rule for target.
pdf-sevenseas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-sevenseas
.PHONY : pdf-sevenseas

# fast build rule for target.
pdf-sevenseas/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-sevenseas.dir/build.make CMakeFiles/pdf-sevenseas.dir/build
.PHONY : pdf-sevenseas/fast

#=============================================================================
# Target rules for targets named png-sevenseas

# Build rule for target.
png-sevenseas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-sevenseas
.PHONY : png-sevenseas

# fast build rule for target.
png-sevenseas/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-sevenseas.dir/build.make CMakeFiles/png-sevenseas.dir/build
.PHONY : png-sevenseas/fast

#=============================================================================
# Target rules for targets named pdf-skygraph

# Build rule for target.
pdf-skygraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-skygraph
.PHONY : pdf-skygraph

# fast build rule for target.
pdf-skygraph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-skygraph.dir/build.make CMakeFiles/pdf-skygraph.dir/build
.PHONY : pdf-skygraph/fast

#=============================================================================
# Target rules for targets named png-skygraph

# Build rule for target.
png-skygraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-skygraph
.PHONY : png-skygraph

# fast build rule for target.
png-skygraph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-skygraph.dir/build.make CMakeFiles/png-skygraph.dir/build
.PHONY : png-skygraph/fast

#=============================================================================
# Target rules for targets named pdf-supersharkomatic

# Build rule for target.
pdf-supersharkomatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-supersharkomatic
.PHONY : pdf-supersharkomatic

# fast build rule for target.
pdf-supersharkomatic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-supersharkomatic.dir/build.make CMakeFiles/pdf-supersharkomatic.dir/build
.PHONY : pdf-supersharkomatic/fast

#=============================================================================
# Target rules for targets named png-supersharkomatic

# Build rule for target.
png-supersharkomatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-supersharkomatic
.PHONY : png-supersharkomatic

# fast build rule for target.
png-supersharkomatic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-supersharkomatic.dir/build.make CMakeFiles/png-supersharkomatic.dir/build
.PHONY : png-supersharkomatic/fast

#=============================================================================
# Target rules for targets named pdf-typhoon

# Build rule for target.
pdf-typhoon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-typhoon
.PHONY : pdf-typhoon

# fast build rule for target.
pdf-typhoon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-typhoon.dir/build.make CMakeFiles/pdf-typhoon.dir/build
.PHONY : pdf-typhoon/fast

#=============================================================================
# Target rules for targets named png-typhoon

# Build rule for target.
png-typhoon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-typhoon
.PHONY : png-typhoon

# fast build rule for target.
png-typhoon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-typhoon.dir/build.make CMakeFiles/png-typhoon.dir/build
.PHONY : png-typhoon/fast

#=============================================================================
# Target rules for targets named pdf-vainqueur

# Build rule for target.
pdf-vainqueur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-vainqueur
.PHONY : pdf-vainqueur

# fast build rule for target.
pdf-vainqueur/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-vainqueur.dir/build.make CMakeFiles/pdf-vainqueur.dir/build
.PHONY : pdf-vainqueur/fast

#=============================================================================
# Target rules for targets named png-vainqueur

# Build rule for target.
png-vainqueur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-vainqueur
.PHONY : png-vainqueur

# fast build rule for target.
png-vainqueur/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-vainqueur.dir/build.make CMakeFiles/png-vainqueur.dir/build
.PHONY : png-vainqueur/fast

#=============================================================================
# Target rules for targets named pdf-verne

# Build rule for target.
pdf-verne: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-verne
.PHONY : pdf-verne

# fast build rule for target.
pdf-verne/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-verne.dir/build.make CMakeFiles/pdf-verne.dir/build
.PHONY : pdf-verne/fast

#=============================================================================
# Target rules for targets named png-verne

# Build rule for target.
png-verne: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-verne
.PHONY : png-verne

# fast build rule for target.
png-verne/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-verne.dir/build.make CMakeFiles/png-verne.dir/build
.PHONY : png-verne/fast

#=============================================================================
# Target rules for targets named pdf-viajero

# Build rule for target.
pdf-viajero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-viajero
.PHONY : pdf-viajero

# fast build rule for target.
pdf-viajero/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-viajero.dir/build.make CMakeFiles/pdf-viajero.dir/build
.PHONY : pdf-viajero/fast

#=============================================================================
# Target rules for targets named png-viajero

# Build rule for target.
png-viajero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-viajero
.PHONY : png-viajero

# fast build rule for target.
png-viajero/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-viajero.dir/build.make CMakeFiles/png-viajero.dir/build
.PHONY : png-viajero/fast

#=============================================================================
# Target rules for targets named pdf-world_timer

# Build rule for target.
pdf-world_timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-world_timer
.PHONY : pdf-world_timer

# fast build rule for target.
pdf-world_timer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-world_timer.dir/build.make CMakeFiles/pdf-world_timer.dir/build
.PHONY : pdf-world_timer/fast

#=============================================================================
# Target rules for targets named png-world_timer

# Build rule for target.
png-world_timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-world_timer
.PHONY : png-world_timer

# fast build rule for target.
png-world_timer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-world_timer.dir/build.make CMakeFiles/png-world_timer.dir/build
.PHONY : png-world_timer/fast

#=============================================================================
# Target rules for targets named pdf-vainqueur_de

# Build rule for target.
pdf-vainqueur_de: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-vainqueur_de
.PHONY : pdf-vainqueur_de

# fast build rule for target.
pdf-vainqueur_de/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-vainqueur_de.dir/build.make CMakeFiles/pdf-vainqueur_de.dir/build
.PHONY : pdf-vainqueur_de/fast

#=============================================================================
# Target rules for targets named png-vainqueur_de

# Build rule for target.
png-vainqueur_de: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-vainqueur_de
.PHONY : png-vainqueur_de

# fast build rule for target.
png-vainqueur_de/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-vainqueur_de.dir/build.make CMakeFiles/png-vainqueur_de.dir/build
.PHONY : png-vainqueur_de/fast

#=============================================================================
# Target rules for targets named pdf-all

# Build rule for target.
pdf-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdf-all
.PHONY : pdf-all

# fast build rule for target.
pdf-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdf-all.dir/build.make CMakeFiles/pdf-all.dir/build
.PHONY : pdf-all/fast

#=============================================================================
# Target rules for targets named png-all

# Build rule for target.
png-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 png-all
.PHONY : png-all

# fast build rule for target.
png-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/png-all.dir/build.make CMakeFiles/png-all.dir/build
.PHONY : png-all/fast

#=============================================================================
# Target rules for targets named all_zines

# Build rule for target.
all_zines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_zines
.PHONY : all_zines

# fast build rule for target.
all_zines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_zines.dir/build.make CMakeFiles/all_zines.dir/build
.PHONY : all_zines/fast

#=============================================================================
# Target rules for targets named clean_zines

# Build rule for target.
clean_zines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_zines
.PHONY : clean_zines

# fast build rule for target.
clean_zines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_zines.dir/build.make CMakeFiles/clean_zines.dir/build
.PHONY : clean_zines/fast

#=============================================================================
# Target rules for targets named help_zines

# Build rule for target.
help_zines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 help_zines
.PHONY : help_zines

# fast build rule for target.
help_zines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/help_zines.dir/build.make CMakeFiles/help_zines.dir/build
.PHONY : help_zines/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all_zines"
	@echo "... clean_zines"
	@echo "... help_zines"
	@echo "... pdf-ala14"
	@echo "... pdf-all"
	@echo "... pdf-bushido"
	@echo "... pdf-caballero"
	@echo "... pdf-colossus"
	@echo "... pdf-competidor"
	@echo "... pdf-cosmotemp"
	@echo "... pdf-decotimer"
	@echo "... pdf-dirty_fifteen"
	@echo "... pdf-ferroviario"
	@echo "... pdf-forest_defender"
	@echo "... pdf-galeno"
	@echo "... pdf-gamma_gibraltar"
	@echo "... pdf-goldmaster"
	@echo "... pdf-grand_belize"
	@echo "... pdf-heian"
	@echo "... pdf-iberia"
	@echo "... pdf-ichi"
	@echo "... pdf-inmortal"
	@echo "... pdf-inmortal_reserva_especial"
	@echo "... pdf-kingtuna"
	@echo "... pdf-majetek"
	@echo "... pdf-monumental"
	@echo "... pdf-okeah"
	@echo "... pdf-racing"
	@echo "... pdf-roquina"
	@echo "... pdf-salto_de_fe"
	@echo "... pdf-sevenseas"
	@echo "... pdf-skygraph"
	@echo "... pdf-supersharkomatic"
	@echo "... pdf-typhoon"
	@echo "... pdf-vainqueur"
	@echo "... pdf-vainqueur_de"
	@echo "... pdf-verne"
	@echo "... pdf-viajero"
	@echo "... pdf-world_timer"
	@echo "... png-ala14"
	@echo "... png-all"
	@echo "... png-bushido"
	@echo "... png-caballero"
	@echo "... png-colossus"
	@echo "... png-competidor"
	@echo "... png-cosmotemp"
	@echo "... png-decotimer"
	@echo "... png-dirty_fifteen"
	@echo "... png-ferroviario"
	@echo "... png-forest_defender"
	@echo "... png-galeno"
	@echo "... png-gamma_gibraltar"
	@echo "... png-goldmaster"
	@echo "... png-grand_belize"
	@echo "... png-heian"
	@echo "... png-iberia"
	@echo "... png-ichi"
	@echo "... png-inmortal"
	@echo "... png-inmortal_reserva_especial"
	@echo "... png-kingtuna"
	@echo "... png-majetek"
	@echo "... png-monumental"
	@echo "... png-okeah"
	@echo "... png-racing"
	@echo "... png-roquina"
	@echo "... png-salto_de_fe"
	@echo "... png-sevenseas"
	@echo "... png-skygraph"
	@echo "... png-supersharkomatic"
	@echo "... png-typhoon"
	@echo "... png-vainqueur"
	@echo "... png-vainqueur_de"
	@echo "... png-verne"
	@echo "... png-viajero"
	@echo "... png-world_timer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

